# Generated by Django 4.1.3 on 2022-11-15 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_ticket_is_cancelled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='booked_by',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='ticket_from',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='ticket_to',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='train',
        ),
        migrations.RemoveField(
            model_name='trainseatchart',
            name='train',
        ),
        migrations.DeleteModel(
            name='Passenger',
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
        migrations.DeleteModel(
            name='TrainSeatChart',
        ),
    ]
