# Generated by Django 4.1.3 on 2022-11-18 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_demo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='train',
            name='classes',
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('pnr', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('journey_date', models.DateField()),
                ('seats', models.IntegerField()),
                ('train_no', models.ForeignKey(max_length=5, on_delete=django.db.models.deletion.CASCADE, to='website.train')),
            ],
        ),
    ]
