# Generated by Django 4.1.3 on 2022-11-18 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_alter_booking_journey_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='destination',
            field=models.ForeignKey(default='banjara', on_delete=django.db.models.deletion.CASCADE, related_name='train_destination_book', to='website.station'),
        ),
        migrations.AddField(
            model_name='booking',
            name='source',
            field=models.ForeignKey(default='banjara', on_delete=django.db.models.deletion.CASCADE, related_name='train_source_book', to='website.station'),
        ),
    ]
