# Generated by Django 4.1.3 on 2022-11-18 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_booking_destination_booking_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='train_destination_book', to='website.station'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='train_source_book', to='website.station'),
        ),
    ]
