# Generated by Django 4.1.3 on 2022-11-18 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_alter_booking_destination_alter_booking_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='destination',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='booking',
            name='source',
            field=models.CharField(max_length=30),
        ),
    ]
